version: '3.1'

services:
  angular: 
    image: frontend
    build: angular-client
    expose:
      - 80
    ports:
      - "80:80"

  express:
    image: api
    restart: always
    build: express-server
    environment:
      NODE_ENV: production
      SERVER_PORT: 3000
      JWT_SECRET: 'e9697d39-b9d0-4bcd-955d-f6f56cdf519a'
      MONGO_HOST: mongodb://admin:pass@mongo/odmp
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    expose:
      - 27017
    ports:
     - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    expose:
      - 8081
    ports:
      - 8081:8081
    depends_on:
      - mongo